// Generated by Wrangler on Tue Aug 06 2024 21:35:16 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	SHOPIFY_SESSIONS: KVNamespace;
	SHOPIFY_API_KEY: string;
	SHOPIFY_API_SECRET: string;
	SCOPES: string;
	SHOPIFY_APP_URL: string;
	SHOP_CUSTOM_DOMAIN: string;
}
